/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.vente;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Hp
 */
public class AdministrationAgent extends javax.swing.JPanel {

    String idPersonnel;
    String choix;
    

    /**
     * Creates new form Agent
     */
    public AdministrationAgent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListAgent = new javax.swing.JList<>();
        jTextFieldIdPersonnel = new javax.swing.JTextField();
        jTextFieldNomPersonnel = new javax.swing.JTextField();
        jTextFieldPernomPersonnel = new javax.swing.JTextField();
        jTextFieldTelPersonnel = new javax.swing.JTextField();
        jTextFieldMailPersonnel = new javax.swing.JTextField();
        jButtonModifier = new javax.swing.JButton();
        jButtonRefresh = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPseudoPersonnel = new javax.swing.JTextField();
        jButtonCreer = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jRadioButtonAdmin = new javax.swing.JRadioButton();
        jRadioButtonAgent = new javax.swing.JRadioButton();
        jPasswordFieldAgent = new javax.swing.JPasswordField();

        jLabel1.setText("id :");

        jLabel2.setText("mdp :");

        jLabel3.setText("nom :");

        jLabel4.setText("prenom :");

        jLabel5.setText("Mail :");

        jLabel6.setText("Tel :");

        jListAgent.setModel(new DefaultListModel());
        jListAgent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListAgentMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jListAgentMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jListAgent);

        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jButtonRefresh.setText("Refresh");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        jLabel7.setText("Pseudo :");

        jButtonCreer.setText("Créer");
        jButtonCreer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreerActionPerformed(evt);
            }
        });

        jLabel8.setText("Profil :");

        jRadioButtonAdmin.setText("Admin");
        jRadioButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAdminActionPerformed(evt);
            }
        });

        jRadioButtonAgent.setText("Agent");
        jRadioButtonAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAgentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldIdPersonnel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jPasswordFieldAgent)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNomPersonnel))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPseudoPersonnel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonRefresh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonModifier)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonCreer)
                                .addGap(0, 51, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldPernomPersonnel)
                                    .addComponent(jTextFieldMailPersonnel)
                                    .addComponent(jTextFieldTelPersonnel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonAdmin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonAgent)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIdPersonnel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jPasswordFieldAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldPseudoPersonnel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldNomPersonnel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPernomPersonnel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldMailPersonnel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldTelPersonnel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButtonAdmin)
                                .addComponent(jRadioButtonAgent)))
                        .addGap(2, 2, 2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModifier)
                    .addComponent(jButtonRefresh)
                    .addComponent(jButtonCreer))
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jListAgentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListAgentMouseClicked
        AfficherAgent();
    }//GEN-LAST:event_jListAgentMouseClicked

    private void jListAgentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListAgentMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jListAgentMouseEntered

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        getAgent();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        setAgent();
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jButtonCreerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreerActionPerformed
creationAgent();
    }//GEN-LAST:event_jButtonCreerActionPerformed

    private void jRadioButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAdminActionPerformed
        choix="1";
    }//GEN-LAST:event_jRadioButtonAdminActionPerformed

    private void jRadioButtonAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAgentActionPerformed
        choix="2";
    }//GEN-LAST:event_jRadioButtonAgentActionPerformed

    public void getAgent() {
        //Innitialisation
        DefaultListModel leModelAgent = (DefaultListModel) jListAgent.getModel();
        //clear des model des listes
        leModelAgent.clear();
        //Requete qui nous donne le nom du produit en fonction de la Recherche précedante et du nom du produit
        String sqlGetAgent = "SELECT * FROM personnel WHERE idProfil = 2";
        ResultSet TuplesGetAgent = DaoSIO.getInstance().requeteSelection(sqlGetAgent);
        try {
            while (TuplesGetAgent.next()) {
                leModelAgent.addElement(TuplesGetAgent.getString("nomPersonnel") + " | " + TuplesGetAgent.getString("prenomPersonnel"));//ajoute le SelectionClient a la liste
            }

        } catch (SQLException ex) {
            Logger.getLogger(SelectionProduit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void AfficherAgent() {
        String Personnel = jListAgent.getSelectedValue();
        String[] PersonnelSplit = Personnel.split(" ");
        String sqlAfficherAgent = "SELECT * FROM personnel WHERE nomPersonnel LIKE '" + PersonnelSplit[0] + "'";
        ResultSet TuplesAfficherAgent = DaoSIO.getInstance().requeteSelection(sqlAfficherAgent);
        try {
            while (TuplesAfficherAgent.next()) {
                jTextFieldIdPersonnel.setText(TuplesAfficherAgent.getString("idPersonnel"));
                jPasswordFieldAgent.setText(TuplesAfficherAgent.getString("mdp"));
                jTextFieldPseudoPersonnel.setText(TuplesAfficherAgent.getString("pseudo"));
                jTextFieldNomPersonnel.setText(TuplesAfficherAgent.getString("nomPersonnel"));
                jTextFieldPernomPersonnel.setText(TuplesAfficherAgent.getString("prenomPersonnel"));
                jTextFieldMailPersonnel.setText(TuplesAfficherAgent.getString("emailPersonnel"));
                jTextFieldTelPersonnel.setText(TuplesAfficherAgent.getString("telPersonnel"));
                idPersonnel = TuplesAfficherAgent.getString("idPersonnel");
            }
        } catch (Exception e) {
        }
    }

    private void setAgent() {

        String idAModifier = jTextFieldIdPersonnel.getText();
        String mdp = jPasswordFieldAgent.getText();
        String email = jTextFieldMailPersonnel.getText();
        String nom = jTextFieldNomPersonnel.getText();
        String prenom = jTextFieldPernomPersonnel.getText();
        String tel = jTextFieldTelPersonnel.getText();
        String pseudo = jTextFieldPseudoPersonnel.getText();
        String sqlSetAgent = "UPDATE `personnel` SET `nomPersonnel`='" + nom + "',`prenomPersonnel`='" + prenom + "',`emailPersonnel`='" + email + "',`telPersonnel`='" + tel + "',`pseudo`='" + pseudo + "',`mdp`='" + mdp + "' WHERE idPersonnel = " + idAModifier;
        int TuplesSetAgent = DaoSIO.getInstance().requeteAction(sqlSetAgent);
        if (TuplesSetAgent == 1) {
            System.out.println("Bien fait pour la tuples SetAgent");
        }

    }

    /**
     * Creation d'un agent
     */
    private void creationAgent() {
        String mdp = jPasswordFieldAgent.getText();
        String email = jTextFieldMailPersonnel.getText();
        String nom = jTextFieldNomPersonnel.getText();
        String prenom = jTextFieldPernomPersonnel.getText();
        String tel = jTextFieldTelPersonnel.getText();
        String pseudo = jTextFieldPseudoPersonnel.getText();
        String idProfil =choix;
        String sqlCreateAgent = "INSERT INTO `personnel` (`nomPersonnel`, `prenomPersonnel`, `emailPersonnel`, `telPersonnel`, `pseudo`, `mdp`, `idProfil`) VALUES ('"+nom+"', '"+prenom+"', '"+email+"', '"+tel+"', '"+pseudo+"', '"+mdp+"', '"+idProfil+"')'";
        int TuplesCreationAgent = DaoSIO.getInstance().requeteAction(sqlCreateAgent);
        if (TuplesCreationAgent == 1) {
            System.out.println("Bien fait pour la création d'un agent");
        }
    }
 


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreer;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jListAgent;
    private javax.swing.JPasswordField jPasswordFieldAgent;
    private javax.swing.JRadioButton jRadioButtonAdmin;
    private javax.swing.JRadioButton jRadioButtonAgent;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldIdPersonnel;
    private javax.swing.JTextField jTextFieldMailPersonnel;
    private javax.swing.JTextField jTextFieldNomPersonnel;
    private javax.swing.JTextField jTextFieldPernomPersonnel;
    private javax.swing.JTextField jTextFieldPseudoPersonnel;
    private javax.swing.JTextField jTextFieldTelPersonnel;
    // End of variables declaration//GEN-END:variables
}
