/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.vente;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Hp
 */
public class AdministrationProfil extends javax.swing.JPanel {
private String idProfil;
    /**
     * Creates new form Profil
     */
    public AdministrationProfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonRefresh = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProfil = new javax.swing.JList<>();
        jTextFieldProfil = new javax.swing.JTextField();

        jLabel1.setText("Profil");

        jLabel3.setText("Label profil");

        jButtonRefresh.setText("Refresh");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jListProfil.setModel(new DefaultListModel());
        jListProfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListProfilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListProfil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jButtonModifier)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jButtonRefresh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonModifier))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        getProfil();
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jListProfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListProfilMouseClicked
        String Profil = jListProfil.getSelectedValue();
        String sqlGetIdd ="SELECT * FROM profil WHERE libelleProfil LIKE '"+Profil+"'";
        ResultSet TuplesGetId = DaoSIO.getInstance().requeteSelection(sqlGetIdd);
    try {
        while (TuplesGetId.next()) {
            idProfil = TuplesGetId.getString("idProfil");
        }
    } catch (SQLException ex) {
        Logger.getLogger(AdministrationProfil.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        jTextFieldProfil.setText(Profil);
        
    }//GEN-LAST:event_jListProfilMouseClicked

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        setProfil();
    }//GEN-LAST:event_jButtonModifierActionPerformed
    /**
     * Permet d'avoir les AdministrationProfil
     */
    public void getProfil() {
        DefaultListModel leModelProfil = (DefaultListModel) jListProfil.getModel();
        leModelProfil.clear();
        String sqlGetProfil = "SELECT * FROM profil";
        ResultSet TuplesGetProfil = DaoSIO.getInstance().requeteSelection(sqlGetProfil);
        try {
            while (TuplesGetProfil.next()) {
                leModelProfil.addElement(TuplesGetProfil.getString("libelleProfil"));

            }
        } catch (SQLException ex) {
        }
    }

    private void setProfil() {
        System.out.println("idProfil = "+idProfil);
        String libelleProfil = jTextFieldProfil.getText();
        String sqlSetProfil1 = "UPDATE `profil` SET `libelleProfil`='" + libelleProfil+"' WHERE idProfil = "+idProfil;
        int TuplesSetProfil1 = DaoSIO.getInstance().requeteAction(sqlSetProfil1);
        if (TuplesSetProfil1 == 1) {
            System.out.println("Bien fait pour Profil 1");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jListProfil;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldProfil;
    // End of variables declaration//GEN-END:variables
}
