/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.vente;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author v.marques
 */
public class AdministrationStatistic extends javax.swing.JPanel {

    /**
     * Creates new form AdministrationStatistic
     */
    public AdministrationStatistic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListProduitRupture = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabelChiffreAffaire = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jListProduitRupture.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jListProduitRupture);

        jLabel1.setText("Chiffre d'affaire :");

        jButton1.setText("Actualiser");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelChiffreAffaire, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabelChiffreAffaire, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       ToutAfficher();

    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * Afficher les produit dont le stock est en dessous de 10.
     */
    public void AfficherListProduitEnRutpure(){
DefaultListModel leModelProduitRupture = (DefaultListModel) jListProduitRupture.getModel();
        //clear des model des listes
        leModelProduitRupture.clear();
        //Requete qui nous donne le nom du produit en fonction de la Recherche précedante et du nom du produit
        String sqlProduitEnRupture = "SELECT * FROM produit ";
        ResultSet TuplesProduitEnRupture = DaoSIO.getInstance().requeteSelection(sqlProduitEnRupture);
        try {
            while (TuplesProduitEnRupture.next()) {
                Integer stock =Integer.parseInt(TuplesProduitEnRupture.getString("stock"));
                if (stock <= 10) {
                    leModelProduitRupture.addElement(TuplesProduitEnRupture.getString("libelleProduit"));//ajoute la categorie a la liste
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(SelectionProduit.class.getName()).log(Level.SEVERE, null, ex);
        }
}
/**
 * Affiche le Chiffre D'affaire des Vente 
 */
public void AfficherChiffreDAffaire(){
String sqlChiffreAffaire ="SELECT SUM(facture) FROM bon_commande";
        ResultSet TuplesChiffreAffaire = DaoSIO.getInstance().requeteSelection(sqlChiffreAffaire);
        try {
            while (TuplesChiffreAffaire.next()) {
                jLabelChiffreAffaire.setText(TuplesChiffreAffaire.getString("SUM(facture)"));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdministrationStatistic.class.getName()).log(Level.SEVERE, null, ex);
        }
}


/**
 * Permet d'afficher la liste et le Chiffred'affaire
 */
public void ToutAfficher(){
AfficherChiffreDAffaire();
AfficherListProduitEnRutpure();
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelChiffreAffaire;
    private javax.swing.JList<String> jListProduitRupture;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
