/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.vente;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Hp
 */
public class AdministrationVente extends javax.swing.JPanel {

    String idPersonnel;
    String idClient;
    
    String jours;
    String mois;
    String annee;
    
    Boolean anneeOK;
    Boolean moisOK;
    Boolean jourOK;
    
    static ResultSet TuplesAfficherVente;

    /**
     * Creates new form AdministrationVente
     */
    public AdministrationVente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListVente = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDateJours = new javax.swing.JTextField();
        jTextFieldDateMois = new javax.swing.JTextField();
        jTextFieldDateAnnee = new javax.swing.JTextField();
        jButtonRecherche = new javax.swing.JButton();
        jPanelVente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelVenteIdVente = new javax.swing.JLabel();
        jLabelVenteDate = new javax.swing.JLabel();
        jLabelVenteIdPersonnel = new javax.swing.JLabel();
        jLabelVenteIdClient = new javax.swing.JLabel();
        jPanelPersonnel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabelPersonnelPrenom = new javax.swing.JLabel();
        jLabelPersonnelIdPersonnel = new javax.swing.JLabel();
        jLabelPersonnelNom = new javax.swing.JLabel();
        jLabelPersonnelEmail = new javax.swing.JLabel();
        jLabelPersonnelTel = new javax.swing.JLabel();
        jLabelPersonnelProfil = new javax.swing.JLabel();
        jPanelClient = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabelClientId = new javax.swing.JLabel();
        jLabelClientNom = new javax.swing.JLabel();
        jLabelClientPrenom = new javax.swing.JLabel();
        jLabelClientEmail = new javax.swing.JLabel();
        jLabelClientTel = new javax.swing.JLabel();

        jListVente.setModel(new DefaultListModel());
        jListVente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListVenteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListVente);

        jLabel2.setText("Jours :");

        jLabel3.setText("Mois :");

        jLabel4.setText("Année :");

        jTextFieldDateJours.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldDateJoursCaretUpdate(evt);
            }
        });

        jTextFieldDateMois.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldDateMoisCaretUpdate(evt);
            }
        });

        jTextFieldDateAnnee.setText("2020");
        jTextFieldDateAnnee.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextFieldDateAnneeCaretUpdate(evt);
            }
        });
        jTextFieldDateAnnee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateAnneeActionPerformed(evt);
            }
        });

        jButtonRecherche.setText("Rechercher");
        jButtonRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRechercheActionPerformed(evt);
            }
        });

        jPanelVente.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Vente");

        jLabel5.setText("idVente :");

        jLabel6.setText("Date :");

        jLabel7.setText("idClient :");

        jLabel8.setText("idPersonnel :");

        javax.swing.GroupLayout jPanelVenteLayout = new javax.swing.GroupLayout(jPanelVente);
        jPanelVente.setLayout(jPanelVenteLayout);
        jPanelVenteLayout.setHorizontalGroup(
            jPanelVenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVenteLayout.createSequentialGroup()
                .addGroup(jPanelVenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVenteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelVenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelVenteLayout.createSequentialGroup()
                                .addGroup(jPanelVenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelVenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelVenteLayout.createSequentialGroup()
                                        .addComponent(jLabelVenteDate, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                        .addGap(1, 1, 1))
                                    .addComponent(jLabelVenteIdPersonnel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelVenteIdClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanelVenteLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelVenteIdVente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanelVenteLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanelVenteLayout.setVerticalGroup(
            jPanelVenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelVenteLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelVenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabelVenteIdVente, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addComponent(jLabelVenteDate, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelVenteIdClient, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelVenteIdPersonnel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelPersonnel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel10.setText("Personnel");

        jLabel11.setText("id Personnel :");

        jLabel12.setText("Nom :");

        jLabel13.setText("Email :");

        jLabel14.setText("Prenom :");

        jLabel15.setText("Profil :");

        jLabel16.setText("Telephone :");

        javax.swing.GroupLayout jPanelPersonnelLayout = new javax.swing.GroupLayout(jPanelPersonnel);
        jPanelPersonnel.setLayout(jPanelPersonnelLayout);
        jPanelPersonnelLayout.setHorizontalGroup(
            jPanelPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonnelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPersonnelPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPersonnelIdPersonnel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPersonnelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPersonnelNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPersonnelTel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPersonnelProfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelPersonnelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel10)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanelPersonnelLayout.setVerticalGroup(
            jPanelPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonnelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPersonnelLayout.createSequentialGroup()
                        .addGroup(jPanelPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabelPersonnelIdPersonnel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabelPersonnelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelPersonnelLayout.createSequentialGroup()
                                .addGroup(jPanelPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabelPersonnelPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))
                            .addComponent(jLabelPersonnelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16))
                    .addComponent(jLabelPersonnelTel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabelPersonnelProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelClient.setBackground(new java.awt.Color(204, 204, 204));

        jLabel9.setText("Client");

        jLabel17.setText("id Client :");

        jLabel18.setText("Nom :");

        jLabel19.setText("Prenom :");

        jLabel20.setText("Email :");

        jLabel21.setText("Telephone :");

        javax.swing.GroupLayout jPanelClientLayout = new javax.swing.GroupLayout(jPanelClient);
        jPanelClient.setLayout(jPanelClientLayout);
        jPanelClientLayout.setHorizontalGroup(
            jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientLayout.createSequentialGroup()
                .addGroup(jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelClientLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel9))
                    .addGroup(jPanelClientLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel19)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelClientId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelClientNom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelClientPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelClientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelClientTel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanelClientLayout.setVerticalGroup(
            jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabelClientId, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelClientLayout.createSequentialGroup()
                        .addGroup(jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18)
                            .addComponent(jLabelClientNom, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addComponent(jLabelClientPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabelClientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelClientTel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jTextFieldDateJours, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jTextFieldDateMois, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDateAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRecherche))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelVente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelPersonnel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldDateJours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldDateMois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldDateAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRecherche))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelVente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelPersonnel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRechercheActionPerformed
        if (anneeOK) {
            annee = jTextFieldDateAnnee.getText();

            if (moisOK) {
                mois = jTextFieldDateMois.getText();
                if (jourOK) {
                    jours = jTextFieldDateJours.getText();
                    afficherVenteDansListAvecPersonnelEtClient();
                    
                }else{JOptionPane.showMessageDialog(null, "Impossible problème au niveau du jour");}
            }else{JOptionPane.showMessageDialog(null, "Impossible problème au niveau du mois");}
        }else{JOptionPane.showMessageDialog(null, "Impossible problème au niveau de l'annee ");}
        
    }//GEN-LAST:event_jButtonRechercheActionPerformed

    /**
 * Vérifie si les année ne dépasse pas les 3000
* @param evt 
 */
    private void jTextFieldDateAnneeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldDateAnneeCaretUpdate
        Integer verificationDate = null;
        verificationDate.parseInt(jTextFieldDateAnnee.getText());
        if (verificationDate > 3000) {
            JOptionPane.showMessageDialog(null, "Trop de numéro. (pas plus de 3000) ");
            jTextFieldDateAnnee.setForeground(Color.red);
            anneeOK = false;
        } else {
            anneeOK = true;
            jTextFieldDateAnnee.setForeground(Color.black);

        }
    }//GEN-LAST:event_jTextFieldDateAnneeCaretUpdate

    /**
 * Vérifie si les mois ne dépasse pas 12
 * @param evt 
 */
    private void jTextFieldDateMoisCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldDateMoisCaretUpdate
        Integer verificationDate = null;
        verificationDate.parseInt(jTextFieldDateMois.getText());
        if (verificationDate > 12) {
            JOptionPane.showMessageDialog(null, "Trop de numéro. (Pas plus de 12)");
            moisOK = false;
            jTextFieldDateMois.setForeground(Color.red);

        } else {
            moisOK = true;
            jTextFieldDateMois.setForeground(Color.black);

        }
    }//GEN-LAST:event_jTextFieldDateMoisCaretUpdate
 
    /**
  * Vérifie si les jours ne dépasse pas 31
*/
    private void jTextFieldDateJoursCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextFieldDateJoursCaretUpdate
        Integer verificationDate = null;
        verificationDate.parseInt(jTextFieldDateJours.getText());
        if (verificationDate > 31) {
            JOptionPane.showMessageDialog(null, "Trop de numéro. (Pas plus de 31)");
            jourOK = false;
            jTextFieldDateJours.setForeground(Color.red);

        } else {
            jourOK = true;
            jTextFieldDateJours.setForeground(Color.black);

        }
    }//GEN-LAST:event_jTextFieldDateJoursCaretUpdate

    private void jTextFieldDateAnneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateAnneeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateAnneeActionPerformed

    private void jListVenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListVenteMouseClicked
        String vente = jListVente.getSelectedValue();
       String [] venteSplit = vente.split("|");
        String sql = "SELECT * FROM `vente` "
                + "INNER JOIN personnel ON vente.idPersonnel = personnel.idPersonnel "
                + "INNER JOIN client ON vente.idClient = client.idClient "
                +"WHERE idVente ='%'"+venteSplit[3] + "'";
        ResultSet Tuples = DaoSIO.getInstance().requeteSelection(sql);
        try {
            while (Tuples.next()) {
                //--------------------------------Partie Vente----------------
                jLabelVenteDate.setText(Tuples.getString("dateVente"));
                jLabelVenteIdVente.setText(Tuples.getString("idVente"));
                jLabelVenteIdClient.setText(Tuples.getString("idClient"));
                jLabelVenteIdPersonnel.setText(Tuples.getString("idPersonnel"));
                //------------------------------------Partie Personnel------------------------------------------------
                jLabelPersonnelEmail.setText(Tuples.getString("mailPersonnel"));
                jLabelPersonnelIdPersonnel.setText(Tuples.getString("idPersonnel"));
                jLabelPersonnelNom.setText(Tuples.getString("nomPersonnel"));
                jLabelPersonnelPrenom.setText(Tuples.getString("prenomPersonnel"));
                jLabelPersonnelProfil.setText(Tuples.getString("idProfil"));
                jLabelPersonnelTel.setText(Tuples.getString("tel"));
                //--------------------------------------Partie Client---------------------------------------------------
                jLabelClientEmail.setText(Tuples.getString("emailClient"));
                jLabelClientId.setText(Tuples.getString("idClient"));
                jLabelClientNom.setText(Tuples.getString("nomClient"));
                jLabelClientPrenom.setText(Tuples.getString("prenomClient"));
                jLabelClientTel.setText(Tuples.getString("telClient"));

//                idClient = Tuples.getString("idClient");
                System.out.println(idClient);
            }
        } catch (SQLException ex) {
            Logger.getLogger(SelectionProduit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jListVenteMouseClicked

    /**
     * Affiche les vente dans une liste
     * a mettre dans Administration (administrationVente1.afficherVenteDansListAvecPersonnelEtClient();)
     */
    public void afficherVenteDansListAvecPersonnelEtClient() {
        //Innitialisation
        DefaultListModel leModelVente = (DefaultListModel) jListVente.getModel();
        //clear des model des listes
        leModelVente.clear();
        //Requete qui nous donne le nom du produit en fonction de la Recherche précedante et du nom du produit
        String sqlAfficherVente = "SELECT * FROM `vente` "
                + "INNER JOIN personnel ON vente.idPersonnel = personnel.idPersonnel "
                + "INNER JOIN client ON vente.idClient = client.idClient "
                +"WHERE dateVente ='%"+annee+"-%"+mois+"-%"+jours+"'";
        TuplesAfficherVente = DaoSIO.getInstance().requeteSelection(sqlAfficherVente);
        try {
            while (TuplesAfficherVente.next()) {
                leModelVente.addElement(TuplesAfficherVente.getString("nomClient") + " | " + TuplesAfficherVente.getString("nomPersonnel")+ " | " + TuplesAfficherVente.getString("dateVente")+ " | " + TuplesAfficherVente.getString("idVente"));//ajoute le SelectionClient a la liste
            }

        } catch (SQLException ex) {
            Logger.getLogger(SelectionProduit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRecherche;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClientEmail;
    private javax.swing.JLabel jLabelClientId;
    private javax.swing.JLabel jLabelClientNom;
    private javax.swing.JLabel jLabelClientPrenom;
    private javax.swing.JLabel jLabelClientTel;
    private javax.swing.JLabel jLabelPersonnelEmail;
    private javax.swing.JLabel jLabelPersonnelIdPersonnel;
    private javax.swing.JLabel jLabelPersonnelNom;
    private javax.swing.JLabel jLabelPersonnelPrenom;
    private javax.swing.JLabel jLabelPersonnelProfil;
    private javax.swing.JLabel jLabelPersonnelTel;
    private javax.swing.JLabel jLabelVenteDate;
    private javax.swing.JLabel jLabelVenteIdClient;
    private javax.swing.JLabel jLabelVenteIdPersonnel;
    private javax.swing.JLabel jLabelVenteIdVente;
    private javax.swing.JList<String> jListVente;
    private javax.swing.JPanel jPanelClient;
    private javax.swing.JPanel jPanelPersonnel;
    private javax.swing.JPanel jPanelVente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldDateAnnee;
    private javax.swing.JTextField jTextFieldDateJours;
    private javax.swing.JTextField jTextFieldDateMois;
    // End of variables declaration//GEN-END:variables
}
