/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.vente;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Hp
 */
public class AdministrationClient extends javax.swing.JPanel {
private String rechercheClient;
    private String client;
    /**
     * idClient de SelectionClient
     */
    public static String idClient;
    /**
     * Creates new form Client
     */
    public AdministrationClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListClient = new javax.swing.JList<>();
        jTextFieldRechercheClient = new javax.swing.JTextField();
        jButtonRechecheClient = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonModifierClient = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNomClient = new javax.swing.JTextField();
        jTextFieldPrenomClient = new javax.swing.JTextField();
        jTextFieldEmailClient = new javax.swing.JTextField();
        jTextFieldTelClient = new javax.swing.JTextField();
        jButtonCreerClient = new javax.swing.JButton();
        jLabelSelectionClient = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldidClient = new javax.swing.JTextField();

        jListClient.setModel(new DefaultListModel());
        jListClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListClientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListClient);

        jButtonRechecheClient.setText("Rechercher");
        jButtonRechecheClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRechecheClientActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom Client :");

        jButtonModifierClient.setText("Modifier");
        jButtonModifierClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierClientActionPerformed(evt);
            }
        });

        jLabel2.setText("Nom :");

        jLabel3.setText("Prenom :");

        jLabel4.setText("Email :");

        jLabel5.setText("Telephone :");

        jTextFieldPrenomClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrenomClientActionPerformed(evt);
            }
        });

        jButtonCreerClient.setText("Créer");
        jButtonCreerClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreerClientActionPerformed(evt);
            }
        });

        jLabel6.setText("id :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSelectionClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonModifierClient)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonCreerClient))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldRechercheClient, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButtonRechecheClient)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldEmailClient, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextFieldPrenomClient, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldNomClient, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                        .addComponent(jTextFieldidClient))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextFieldTelClient, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldRechercheClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRechecheClient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldidClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldNomClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldPrenomClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEmailClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldTelClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModifierClient)
                    .addComponent(jButtonCreerClient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSelectionClient, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPrenomClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrenomClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrenomClientActionPerformed
/**
 * affiche les information du client 
 * @param evt 
 */
    private void jListClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListClientMouseClicked
        client = jListClient.getSelectedValue();
       String [] clientSplit = client.split(" ");
        String sql = "SELECT * FROM client WHERE nomClient LIKE '" + clientSplit[0] + "'";
        ResultSet Tuples = DaoSIO.getInstance().requeteSelection(sql);
        try {
            while (Tuples.next()) {
                jTextFieldNomClient.setText(Tuples.getString("nomClient"));
                jTextFieldPrenomClient.setText(Tuples.getString("prenomClient"));
                jTextFieldEmailClient.setText(Tuples.getString("emailClient"));
                jTextFieldTelClient.setText(Tuples.getString("telClient"));
                jTextFieldidClient.setText(Tuples.getString("idClient"));
                idClient = Tuples.getString("idClient");
            }
        } catch (SQLException ex) {
            Logger.getLogger(SelectionProduit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jListClientMouseClicked

    private void jButtonRechecheClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRechecheClientActionPerformed
    afficherClientDansList();
    rechercheClient = "%";
    }//GEN-LAST:event_jButtonRechecheClientActionPerformed

    private void jButtonCreerClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreerClientActionPerformed
        CreerClient();
        afficherClientDansList();
    }//GEN-LAST:event_jButtonCreerClientActionPerformed

    private void jButtonModifierClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierClientActionPerformed
//        rechercheClient ="%";
        ModifierClient();
        afficherClientDansList();
    }//GEN-LAST:event_jButtonModifierClientActionPerformed
    /**
     * Affiche les clients dans la list.
     */
    public void afficherClientDansList() {
        //Innitialisation
        rechercheClient = jTextFieldRechercheClient.getText();
        DefaultListModel leModelClient = (DefaultListModel) jListClient.getModel();
        //clear des model des listes
        leModelClient.clear();
        //Requete qui nous donne le nom du produit en fonction de la Recherche précedante et du nom du produit
        String sql = "SELECT * FROM client WHERE nomClient lIKE '%"+rechercheClient+"%'";
        ResultSet Tuples = DaoSIO.getInstance().requeteSelection(sql);
        try {
            while (Tuples.next()) {
                leModelClient.addElement(Tuples.getString("nomClient")+" | "+Tuples.getString("prenomClient"));//ajoute le SelectionClient a la liste
            }

        } catch (SQLException ex) {
            Logger.getLogger(SelectionProduit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * Modifie le client
     */
    private void ModifierClient(){
       String nomClient = jTextFieldNomClient.getText();
       String prenomClient = jTextFieldPrenomClient.getText();
       String emailClient = jTextFieldEmailClient.getText();
       String telClient = jTextFieldTelClient.getText();
    String sql ="UPDATE `client` SET `nomClient`='"+nomClient+"',`prenomClient`='"+prenomClient+"',`emailClient`='"+emailClient+"',`telClient`='"+telClient+"' WHERE idClient = "+idClient;
    int Tuples = DaoSIO.getInstance().requeteAction(sql);
        if (Tuples == 1) {
            System.out.println("Bien fait");
        }
    }
    
    /**
     * Créer un client
     */
    private void CreerClient(){
           String nomClient = jTextFieldNomClient.getText();
       String prenomClient = jTextFieldPrenomClient.getText();
       String emailClient = jTextFieldEmailClient.getText();
       String telClient = jTextFieldTelClient.getText();
    String sql ="INSERT INTO `client`(`nomClient`, `prenomClient`, `emailClient`, `telClient`) VALUES ('"+nomClient+"','"+prenomClient+"','"+emailClient+"','"+telClient+"')";
    int Tuples = DaoSIO.getInstance().requeteAction(sql);
        if (Tuples == 1) {
            System.out.println("Bien fait");
        }
    
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreerClient;
    private javax.swing.JButton jButtonModifierClient;
    private javax.swing.JButton jButtonRechecheClient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelSelectionClient;
    private javax.swing.JList<String> jListClient;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldEmailClient;
    private javax.swing.JTextField jTextFieldNomClient;
    private javax.swing.JTextField jTextFieldPrenomClient;
    private javax.swing.JTextField jTextFieldRechercheClient;
    private javax.swing.JTextField jTextFieldTelClient;
    private javax.swing.JTextField jTextFieldidClient;
    // End of variables declaration//GEN-END:variables
}
